---------------------------------------------------------------------
--
-- Copyright 2021 Ettus Research, A National Instruments Brand
-- SPDX-License-Identifier: LGPL-3.0-or-later
--
-- Module: PkgDB_CONTROL_REGMAP.vhd
--
-- Purpose:
--   The constants in this file are autogenerated by XmlParse.
--
----------------------------------------------------------------------
library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

package PkgDB_CONTROL_REGMAP is

--===============================================================================
-- A numerically ordered list of registers and their HDL source files
--===============================================================================

  -- ATR_CONTROLLER_REGS : 0x0 (zr_top_cpld.v)
  -- LO_CONTROL_REGS     : 0x20 (zr_top_cpld.v)
  -- LED_SETUP_REGS      : 0x400 (zr_top_cpld.v)
  -- SWITCH_SETUP_REGS   : 0x1000 (zr_top_cpld.v)
  -- DSA_SETUP_REGS      : 0x2000 (zr_top_cpld.v)

--===============================================================================
-- RegTypes
--===============================================================================

--===============================================================================
-- Register Group DB_CONTROL_WINDOWS
--===============================================================================

  -- ATR_CONTROLLER_REGS Window (from zr_top_cpld.v)
  constant kATR_CONTROLLER_REGS : integer := 16#0#; -- Window Offset
  constant kATR_CONTROLLER_REGSSize: integer := 16#20#;  -- size in bytes
  --function kATR_CONTROLLER_REGSRec return XReg2_t; -- Window Record function commented out due to programmable attributes

  -- LO_CONTROL_REGS Window (from zr_top_cpld.v)
  constant kLO_CONTROL_REGS : integer := 16#20#; -- Window Offset
  constant kLO_CONTROL_REGSSize: integer := 16#3E0#;  -- size in bytes
  --function kLO_CONTROL_REGSRec return XReg2_t; -- Window Record function commented out due to programmable attributes

  -- LED_SETUP_REGS Window (from zr_top_cpld.v)
  constant kLED_SETUP_REGS : integer := 16#400#; -- Window Offset
  constant kLED_SETUP_REGSSize: integer := 16#C00#;  -- size in bytes
  --function kLED_SETUP_REGSRec return XReg2_t; -- Window Record function commented out due to programmable attributes

  -- SWITCH_SETUP_REGS Window (from zr_top_cpld.v)
  constant kSWITCH_SETUP_REGS : integer := 16#1000#; -- Window Offset
  constant kSWITCH_SETUP_REGSSize: integer := 16#1000#;  -- size in bytes
  --function kSWITCH_SETUP_REGSRec return XReg2_t; -- Window Record function commented out due to programmable attributes

  -- DSA_SETUP_REGS Window (from zr_top_cpld.v)
  constant kDSA_SETUP_REGS : integer := 16#2000#; -- Window Offset
  constant kDSA_SETUP_REGSSize: integer := 16#3000#;  -- size in bytes
  --function kDSA_SETUP_REGSRec return XReg2_t; -- Window Record function commented out due to programmable attributes

--===============================================================================
-- Register Group REGISTER_ENDPOINTS
--===============================================================================

  -- Enumerated type REGISTER_BLOCKS
  constant kREGISTER_BLOCKSSize : integer := 5;
  constant kATR_REGISTERS : integer := 0;  -- REGISTER_BLOCKS:ATR_REGISTERS
  constant kLED_REGISTERS : integer := 1;  -- REGISTER_BLOCKS:LED_REGISTERS
  constant kLO_SPI        : integer := 2;  -- REGISTER_BLOCKS:LO_SPI
  constant kSW_CONTROL    : integer := 3;  -- REGISTER_BLOCKS:SW_CONTROL
  constant kDSA_CONTROL   : integer := 4;  -- REGISTER_BLOCKS:DSA_CONTROL

end package;

package body PkgDB_CONTROL_REGMAP is

  -- function kATR_CONTROLLER_REGSRec not implemented because ATR_CONTROLLER_REGS has programmable attributes
  ---- Return the record of window kATR_CONTROLLER_REGS
  --function kATR_CONTROLLER_REGSRec return XReg2_t is
  --  variable Rec : XReg2_t;
  --begin
  --  Rec := kXRegDefault;
  --  Rec.version := 1;
  --  Rec.offset := XAddrResize(X"0");
  --  Rec.size := kATR_CONTROLLER_REGSSize;
  --  Rec.readable := true;
  --  Rec.writable := true;
  --  Rec.wmask := XRegResize(X"00");
  --  Rec.rmask := XRegResize(X"00");
  --  Rec.strobemask := XRegResize(X"00");
  --  Rec.clearablemask := XRegResize(X"00");
  --  Rec.iswin := true;
  --  --synopsys translate_off
  --  Rec.name := rs("ATR_CONTROLLER_REGS");
  --  --synopsys translate_on
  --  return Rec;
  --end function kATR_CONTROLLER_REGSRec;

  -- function kLO_CONTROL_REGSRec not implemented because LO_CONTROL_REGS has programmable attributes
  ---- Return the record of window kLO_CONTROL_REGS
  --function kLO_CONTROL_REGSRec return XReg2_t is
  --  variable Rec : XReg2_t;
  --begin
  --  Rec := kXRegDefault;
  --  Rec.version := 1;
  --  Rec.offset := XAddrResize(X"20");
  --  Rec.size := kLO_CONTROL_REGSSize;
  --  Rec.readable := true;
  --  Rec.writable := true;
  --  Rec.wmask := XRegResize(X"00");
  --  Rec.rmask := XRegResize(X"00");
  --  Rec.strobemask := XRegResize(X"00");
  --  Rec.clearablemask := XRegResize(X"00");
  --  Rec.iswin := true;
  --  --synopsys translate_off
  --  Rec.name := rs("LO_CONTROL_REGS");
  --  --synopsys translate_on
  --  return Rec;
  --end function kLO_CONTROL_REGSRec;

  -- function kLED_SETUP_REGSRec not implemented because LED_SETUP_REGS has programmable attributes
  ---- Return the record of window kLED_SETUP_REGS
  --function kLED_SETUP_REGSRec return XReg2_t is
  --  variable Rec : XReg2_t;
  --begin
  --  Rec := kXRegDefault;
  --  Rec.version := 1;
  --  Rec.offset := XAddrResize(X"400");
  --  Rec.size := kLED_SETUP_REGSSize;
  --  Rec.readable := true;
  --  Rec.writable := true;
  --  Rec.wmask := XRegResize(X"00");
  --  Rec.rmask := XRegResize(X"00");
  --  Rec.strobemask := XRegResize(X"00");
  --  Rec.clearablemask := XRegResize(X"00");
  --  Rec.iswin := true;
  --  --synopsys translate_off
  --  Rec.name := rs("LED_SETUP_REGS");
  --  --synopsys translate_on
  --  return Rec;
  --end function kLED_SETUP_REGSRec;

  -- function kSWITCH_SETUP_REGSRec not implemented because SWITCH_SETUP_REGS has programmable attributes
  ---- Return the record of window kSWITCH_SETUP_REGS
  --function kSWITCH_SETUP_REGSRec return XReg2_t is
  --  variable Rec : XReg2_t;
  --begin
  --  Rec := kXRegDefault;
  --  Rec.version := 1;
  --  Rec.offset := XAddrResize(X"1000");
  --  Rec.size := kSWITCH_SETUP_REGSSize;
  --  Rec.readable := true;
  --  Rec.writable := true;
  --  Rec.wmask := XRegResize(X"00");
  --  Rec.rmask := XRegResize(X"00");
  --  Rec.strobemask := XRegResize(X"00");
  --  Rec.clearablemask := XRegResize(X"00");
  --  Rec.iswin := true;
  --  --synopsys translate_off
  --  Rec.name := rs("SWITCH_SETUP_REGS");
  --  --synopsys translate_on
  --  return Rec;
  --end function kSWITCH_SETUP_REGSRec;

  -- function kDSA_SETUP_REGSRec not implemented because DSA_SETUP_REGS has programmable attributes
  ---- Return the record of window kDSA_SETUP_REGS
  --function kDSA_SETUP_REGSRec return XReg2_t is
  --  variable Rec : XReg2_t;
  --begin
  --  Rec := kXRegDefault;
  --  Rec.version := 1;
  --  Rec.offset := XAddrResize(X"2000");
  --  Rec.size := kDSA_SETUP_REGSSize;
  --  Rec.readable := true;
  --  Rec.writable := true;
  --  Rec.wmask := XRegResize(X"00");
  --  Rec.rmask := XRegResize(X"00");
  --  Rec.strobemask := XRegResize(X"00");
  --  Rec.clearablemask := XRegResize(X"00");
  --  Rec.iswin := true;
  --  --synopsys translate_off
  --  Rec.name := rs("DSA_SETUP_REGS");
  --  --synopsys translate_on
  --  return Rec;
  --end function kDSA_SETUP_REGSRec;

end package body;
