---------------------------------------------------------------------
--
-- Copyright 2021 Ettus Research, A National Instruments Brand
-- SPDX-License-Identifier: LGPL-3.0-or-later
--
-- Module: PkgCORE_REGS_REGMAP.vhd
--
-- Purpose:
--   The constants in this file are autogenerated by XmlParse.
--
----------------------------------------------------------------------
library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

package PkgCORE_REGS_REGMAP is

--===============================================================================
-- A numerically ordered list of registers and their HDL source files
--===============================================================================

  -- GLOBAL_REGS     : 0x0 (x4xx_core_common.v)
  -- VERSIONING_REGS : 0xC00 (x4xx_core_common.v)
  -- TIMEKEEPER      : 0x1000 (x4xx_core_common.v)
  -- DIO             : 0x2000 (x4xx_core_common.v)

--===============================================================================
-- RegTypes
--===============================================================================

--===============================================================================
-- Register Group CORE_REGS
--===============================================================================

  -- GLOBAL_REGS Window (from x4xx_core_common.v)
  constant kGLOBAL_REGS : integer := 16#0#; -- Window Offset
  constant kGLOBAL_REGSSize: integer := 16#C00#;  -- size in bytes
  --function kGLOBAL_REGSRec return XReg2_t; -- Window Record function commented out due to programmable attributes

  -- VERSIONING_REGS Window (from x4xx_core_common.v)
  constant kVERSIONING_REGS : integer := 16#C00#; -- Window Offset
  constant kVERSIONING_REGSSize: integer := 16#400#;  -- size in byte
  --function kVERSIONING_REGSRec return XReg2_t; -- Window Record function commented out due to programmable attributes

  -- TIMEKEEPER Window (from x4xx_core_common.v)
  constant kTIMEKEEPER : integer := 16#1000#; -- Window Offset
  constant kTIMEKEEPERSize: integer := 16#20#;  -- size in bytes
  --function kTIMEKEEPERRec return XReg2_t; -- Window Record function commented out due to programmable attributes

  -- DIO Window (from x4xx_core_common.v)
  constant kDIO : integer := 16#2000#; -- Window Offset
  constant kDIOSize: integer := 16#20#;  -- size in bytes
  --function kDIORec return XReg2_t; -- Window Record function commented out due to programmable attributes

end package;

package body PkgCORE_REGS_REGMAP is

  -- function kGLOBAL_REGSRec not implemented because GLOBAL_REGS has programmable attributes
  ---- Return the record of window kGLOBAL_REGS
  --function kGLOBAL_REGSRec return XReg2_t is
  --  variable Rec : XReg2_t;
  --begin
  --  Rec := kXRegDefault;
  --  Rec.version := 1;
  --  Rec.offset := XAddrResize(X"0");
  --  Rec.size := kGLOBAL_REGSSize;
  --  Rec.readable := true;
  --  Rec.writable := true;
  --  Rec.wmask := XRegResize(X"00");
  --  Rec.rmask := XRegResize(X"00");
  --  Rec.strobemask := XRegResize(X"00");
  --  Rec.clearablemask := XRegResize(X"00");
  --  Rec.iswin := true;
  --  --synopsys translate_off
  --  Rec.name := rs("GLOBAL_REGS");
  --  --synopsys translate_on
  --  return Rec;
  --end function kGLOBAL_REGSRec;

  -- function kVERSIONING_REGSRec not implemented because VERSIONING_REGS has programmable attributes
  ---- Return the record of window kVERSIONING_REGS
  --function kVERSIONING_REGSRec return XReg2_t is
  --  variable Rec : XReg2_t;
  --begin
  --  Rec := kXRegDefault;
  --  Rec.version := 1;
  --  Rec.offset := XAddrResize(X"C00");
  --  Rec.size := kVERSIONING_REGSSize;
  --  Rec.readable := true;
  --  Rec.writable := true;
  --  Rec.wmask := XRegResize(X"00");
  --  Rec.rmask := XRegResize(X"00");
  --  Rec.strobemask := XRegResize(X"00");
  --  Rec.clearablemask := XRegResize(X"00");
  --  Rec.iswin := true;
  --  --synopsys translate_off
  --  Rec.name := rs("VERSIONING_REGS");
  --  --synopsys translate_on
  --  return Rec;
  --end function kVERSIONING_REGSRec;

  -- function kTIMEKEEPERRec not implemented because TIMEKEEPER has programmable attributes
  ---- Return the record of window kTIMEKEEPER
  --function kTIMEKEEPERRec return XReg2_t is
  --  variable Rec : XReg2_t;
  --begin
  --  Rec := kXRegDefault;
  --  Rec.version := 1;
  --  Rec.offset := XAddrResize(X"1000");
  --  Rec.size := kTIMEKEEPERSize;
  --  Rec.readable := true;
  --  Rec.writable := true;
  --  Rec.wmask := XRegResize(X"00");
  --  Rec.rmask := XRegResize(X"00");
  --  Rec.strobemask := XRegResize(X"00");
  --  Rec.clearablemask := XRegResize(X"00");
  --  Rec.iswin := true;
  --  --synopsys translate_off
  --  Rec.name := rs("TIMEKEEPER");
  --  --synopsys translate_on
  --  return Rec;
  --end function kTIMEKEEPERRec;

  -- function kDIORec not implemented because DIO has programmable attributes
  ---- Return the record of window kDIO
  --function kDIORec return XReg2_t is
  --  variable Rec : XReg2_t;
  --begin
  --  Rec := kXRegDefault;
  --  Rec.version := 1;
  --  Rec.offset := XAddrResize(X"2000");
  --  Rec.size := kDIOSize;
  --  Rec.readable := true;
  --  Rec.writable := true;
  --  Rec.wmask := XRegResize(X"00");
  --  Rec.rmask := XRegResize(X"00");
  --  Rec.strobemask := XRegResize(X"00");
  --  Rec.clearablemask := XRegResize(X"00");
  --  Rec.iswin := true;
  --  --synopsys translate_off
  --  Rec.name := rs("DIO");
  --  --synopsys translate_on
  --  return Rec;
  --end function kDIORec;

end package body;
