# Enable reconvergence checking
cdc reconvergence on
cdc preference reconvergence -depth 1


###############################################################################
# Clocks
###############################################################################

# Top-level clock inputs
netlist clock -group ref_clk       -period  40.000 [list BASE_REFCLK_FPGA_P BASE_REFCLK_FPGA_N]
netlist clock -group pll_ref_clk   -period  15.625 [list PLL_REFCLK_FPGA_P PLL_REFCLK_FPGA_N]
netlist clock -group mgt_ref_clk0  -period   6.400 [list MGT_REFCLK_LMK0_P MGT_REFCLK_LMK0_N]
netlist clock -group mgt_ref_clk3  -period   6.400 [list MGT_REFCLK_LMK3_P MGT_REFCLK_LMK3_N]

# Clocks generated by the same PS DPLL
netlist clock -group ps_clk        -period  25.000 x4xx_ps_rfdc_bd_i.pl_clk40
netlist clock -group ps_clk        -period  10.000 x4xx_ps_rfdc_bd_i.pl_clk100
netlist clock -group ps_clk        -period   5.000 x4xx_ps_rfdc_bd_i.pl_clk200

# Derived from pll_ref_clk
netlist clock -group pll_ref_clk   -period  15.625 x4xx_ps_rfdc_bd_i.pll_ref_clk_out
netlist clock -group pll_ref_clk   -period   7.812 x4xx_ps_rfdc_bd_i.data_clk
netlist clock -group pll_ref_clk   -period   3.906 x4xx_ps_rfdc_bd_i.data_clk_2x
netlist clock -group pll_ref_clk   -period   5.208 x4xx_ps_rfdc_bd_i.rfdc_clk
netlist clock -group pll_ref_clk   -period   2.604 x4xx_ps_rfdc_bd_i.rfdc_clk_2x

# Virtual clock for async signals
netlist clock -group VAsyncClk  -period 100.000 -virtual VAsyncClk


###############################################################################
# Top-level Port Clock Domains
###############################################################################

#######################################
# These signals go into black boxes 
# and aren't being analyzed.

# Clocking and sync
netlist port domain -clock VAsyncClk [list SYSREF_RF_P]
netlist port domain -clock VAsyncClk [list SYSREF_RF_N]
netlist port domain -clock VAsyncClk [list ADC_CLK_P]
netlist port domain -clock VAsyncClk [list ADC_CLK_N]
netlist port domain -clock VAsyncClk [list DAC_CLK_P]
netlist port domain -clock VAsyncClk [list DAC_CLK_N]

# Analog ports
netlist port domain -clock VAsyncClk [list DB0_RX_P]
netlist port domain -clock VAsyncClk [list DB0_RX_N]
netlist port domain -clock VAsyncClk [list DB1_RX_P]
netlist port domain -clock VAsyncClk [list DB1_RX_N]
netlist port domain -clock VAsyncClk [list DB0_TX_P]
netlist port domain -clock VAsyncClk [list DB0_TX_N]
netlist port domain -clock VAsyncClk [list DB1_TX_P]
netlist port domain -clock VAsyncClk [list DB1_TX_N]

# MGT Reference Clocks
netlist port domain -clock VAsyncClk [list MGT_REFCLK_LMK1_P MGT_REFCLK_LMK1_N]
netlist port domain -clock VAsyncClk [list MGT_REFCLK_LMK2_P MGT_REFCLK_LMK2_N]

# Synchronization sysref
netlist port domain -clock VAsyncClk [list SYSREF_FABRIC_P]
netlist port domain -clock VAsyncClk [list SYSREF_FABRIC_N]

# QSFP signals
netlist port domain -clock VAsyncClk [list QSFP0_0_RX_P]
netlist port domain -clock VAsyncClk [list QSFP0_0_RX_N]
netlist port domain -clock VAsyncClk [list QSFP0_1_RX_P]
netlist port domain -clock VAsyncClk [list QSFP0_1_RX_N]
netlist port domain -clock VAsyncClk [list QSFP0_2_RX_P]
netlist port domain -clock VAsyncClk [list QSFP0_2_RX_N]
netlist port domain -clock VAsyncClk [list QSFP0_3_RX_P]
netlist port domain -clock VAsyncClk [list QSFP0_3_RX_N]
netlist port domain -clock VAsyncClk [list QSFP0_0_TX_P]
netlist port domain -clock VAsyncClk [list QSFP0_0_TX_N]
netlist port domain -clock VAsyncClk [list QSFP0_1_TX_P]
netlist port domain -clock VAsyncClk [list QSFP0_1_TX_N]
netlist port domain -clock VAsyncClk [list QSFP0_2_TX_P]
netlist port domain -clock VAsyncClk [list QSFP0_2_TX_N]
netlist port domain -clock VAsyncClk [list QSFP0_3_TX_P]
netlist port domain -clock VAsyncClk [list QSFP0_3_TX_N]

#######################################

netlist port domain -clock base_ref_clk [list PPS_IN]
netlist port domain -clock pll_ref_clk  [list PL_CPLD_MISO]
netlist port domain -clock VAsyncClk    [list FPGA_AUX_REF]
netlist port domain -clock VAsyncClk    [list QSFP0_MODPRS_n]
netlist port domain -clock VAsyncClk    [list QSFP1_MODPRS_n]
netlist port domain -clock pll_ref_clk  [list DB0_SYNTH_SYNC]
netlist port domain -clock pll_ref_clk  [list DB1_SYNTH_SYNC]
netlist port domain -clock base_ref_clk [list LMK_SYNC]
netlist port domain -clock pll_ref_clk  [list PL_CPLD_SCLK]
netlist port domain -clock pll_ref_clk  [list PL_CPLD_MOSI]
netlist port domain -clock pll_ref_clk  [list FABRIC_CLK_OUT_P]
netlist port domain -clock pll_ref_clk  [list FABRIC_CLK_OUT_N]
netlist port domain -clock VAsyncClk    [list QSFP0_RESET_n]
netlist port domain -clock VAsyncClk    [list QSFP0_LPMODE_n]
netlist port domain -clock VAsyncClk    [list QSFP1_RESET_n]
netlist port domain -clock VAsyncClk    [list QSFP1_LPMODE_n]
netlist port domain -clock VAsyncClk    [list CPLD_JTAG_OE_n]
netlist port domain -clock VAsyncClk    [list PPS_LED]
netlist port domain -clock VAsyncClk    [list PL_CPLD_JTAGEN]
netlist port domain -clock pll_ref_clk  [list PL_CPLD_CS0_n]
netlist port domain -clock pll_ref_clk  [list PL_CPLD_CS1_n]
netlist port domain -clock pll_ref_clk  [list DB0_GPIO]
netlist port domain -clock pll_ref_clk  [list DB1_GPIO]
netlist port domain -clock ps_clk       [list DIOA_FPGA]
netlist port domain -clock ps_clk       [list DIOB_FPGA]
netlist port domain -clock base_ref_clk [list TRIG_IO]

# Asynchronous output ports (should be glitch-free)
cdc port attribute -external_sync [list \
    LMK_SYNC       \
    QSFP0_RESET_n  \
    QSFP0_LPMODE_n \
    QSFP1_RESET_n  \
    QSFP1_LPMODE_n \
    CPLD_JTAG_OE_n \
    PPS_LED        \
    TRIG_IO        \
    PL_CPLD_JTAGEN \
    PL_CPLD_CS0_n  \
    PL_CPLD_CS1_n  \
]


###############################################################################
# Resets
###############################################################################

# pl_resetn0 is used in a synchronous and asynchronous fashion
netlist reset -group aReset -async -active_low x4xx_ps_rfdc_bd_i.pl_resetn0

# Black box resets (driven by aReset)
netlist reset -group aReset -sync -async -active_high {x4xx_qsfp_wrapper_0.x4xx_qsfp_wrapper_i.mgt_lanes.lane_loop[0].x4xx_mgt_io_core_i.mgt_rst}
netlist reset -group aReset -sync -async -active_high {x4xx_qsfp_wrapper_0.x4xx_qsfp_wrapper_i.mgt_lanes.lane_loop[1].x4xx_mgt_io_core_i.mgt_rst}
netlist reset -group aReset -sync -async -active_high {x4xx_qsfp_wrapper_0.x4xx_qsfp_wrapper_i.mgt_lanes.lane_loop[2].x4xx_mgt_io_core_i.mgt_rst}
netlist reset -group aReset -sync -async -active_high {x4xx_qsfp_wrapper_0.x4xx_qsfp_wrapper_i.mgt_lanes.lane_loop[3].x4xx_mgt_io_core_i.mgt_rst}
netlist reset -group aReset -sync -async -active_high {x4xx_qsfp_wrapper_1.x4xx_qsfp_wrapper_i.mgt_lanes.lane_loop[0].x4xx_mgt_io_core_i.mgt_rst}
netlist reset -group aReset -sync -async -active_high {x4xx_qsfp_wrapper_1.x4xx_qsfp_wrapper_i.mgt_lanes.lane_loop[1].x4xx_mgt_io_core_i.mgt_rst}
netlist reset -group aReset -sync -async -active_high {x4xx_qsfp_wrapper_1.x4xx_qsfp_wrapper_i.mgt_lanes.lane_loop[2].x4xx_mgt_io_core_i.mgt_rst}
netlist reset -group aReset -sync -async -active_high {x4xx_qsfp_wrapper_1.x4xx_qsfp_wrapper_i.mgt_lanes.lane_loop[3].x4xx_mgt_io_core_i.mgt_rst}

# QPLL resets
netlist reset -group qpll0_reset -async -active_high x4xx_qsfp_wrapper_0.x4xx_qsfp_wrapper_i.qpll0_reset
netlist reset -group qpll1_reset -async -active_high x4xx_qsfp_wrapper_0.x4xx_qsfp_wrapper_i.qpll1_reset

# RFNoC block resets
# These resets get synchronized in each block.
netlist reset -group rfnoc_chdr_rst -sync -async -active_low  x4xx_core_i.rfnoc_image_core_i.b_ddc0_1.noc_shell_ddc_i.backend_iface_i.soft_chdr_rst_stretch_i.state
netlist reset -group rfnoc_ctrl_rst -sync -async -active_low  x4xx_core_i.rfnoc_image_core_i.b_ddc0_1.noc_shell_ddc_i.backend_iface_i.soft_ctrl_rst_stretch_i.state
netlist reset -group ce_rst         -sync -async -active_low  x4xx_core_i.rfnoc_image_core_i.b_ddc0_1.noc_shell_ddc_i.pulse_stretch_min_ce.state
netlist reset -group rfnoc_chdr_rst -sync -async -active_low  x4xx_core_i.rfnoc_image_core_i.b_ddc1_4.noc_shell_ddc_i.backend_iface_i.soft_chdr_rst_stretch_i.state
netlist reset -group rfnoc_ctrl_rst -sync -async -active_low  x4xx_core_i.rfnoc_image_core_i.b_ddc1_4.noc_shell_ddc_i.backend_iface_i.soft_ctrl_rst_stretch_i.state
netlist reset -group ce_rst         -sync -async -active_low  x4xx_core_i.rfnoc_image_core_i.b_ddc1_4.noc_shell_ddc_i.pulse_stretch_min_ce.state
netlist reset -group rfnoc_chdr_rst -sync -async -active_low  x4xx_core_i.rfnoc_image_core_i.b_duc0_0.noc_shell_duc_i.backend_iface_i.soft_chdr_rst_stretch_i.state
netlist reset -group rfnoc_ctrl_rst -sync -async -active_low  x4xx_core_i.rfnoc_image_core_i.b_duc0_0.noc_shell_duc_i.backend_iface_i.soft_ctrl_rst_stretch_i.state
netlist reset -group ce_rst         -sync -async -active_low  x4xx_core_i.rfnoc_image_core_i.b_duc0_0.noc_shell_duc_i.pulse_stretch_min_ce.state
netlist reset -group rfnoc_chdr_rst -sync -async -active_high x4xx_core_i.rfnoc_image_core_i.b_duc1_3.noc_shell_duc_i.backend_iface_i.rfnoc_chdr_rst
netlist reset -group rfnoc_ctrl_rst -sync -async -active_low  x4xx_core_i.rfnoc_image_core_i.b_duc1_3.noc_shell_duc_i.backend_iface_i.soft_ctrl_rst_stretch_i.state
netlist reset -group ce_rst         -sync -async -active_low  x4xx_core_i.rfnoc_image_core_i.b_duc1_3.noc_shell_duc_i.pulse_stretch_min_ce.state
netlist reset -group rfnoc_chdr_rst -sync -async -active_low  x4xx_core_i.rfnoc_image_core_i.b_duc1_3.noc_shell_duc_i.backend_iface_i.soft_chdr_rst_stretch_i.state
netlist reset -group rfnoc_chdr_rst -sync -async -active_high x4xx_core_i.rfnoc_image_core_i.b_radio0_2.noc_shell_radio_i.backend_iface_i.rfnoc_chdr_rst
netlist reset -group rfnoc_ctrl_rst -sync -async -active_low  x4xx_core_i.rfnoc_image_core_i.b_radio0_2.noc_shell_radio_i.backend_iface_i.soft_ctrl_rst_stretch_i.state
netlist reset -group radio_rst      -sync -async -active_low  x4xx_core_i.rfnoc_image_core_i.b_radio0_2.noc_shell_radio_i.pulse_stretch_min_radio.state
netlist reset -group rfnoc_chdr_rst -sync -async -active_high x4xx_core_i.rfnoc_image_core_i.b_radio0_2.noc_shell_radio_i.rfnoc_chdr_rst
netlist reset -group rfnoc_chdr_rst -sync -async -active_low  x4xx_core_i.rfnoc_image_core_i.b_radio0_2.noc_shell_radio_i.backend_iface_i.soft_chdr_rst_stretch_i.state
netlist reset -group rfnoc_ctrl_rst -sync -async -active_low  x4xx_core_i.rfnoc_image_core_i.b_radio1_5.noc_shell_radio_i.backend_iface_i.soft_ctrl_rst_stretch_i.state
netlist reset -group radio_rst      -sync -async -active_low  x4xx_core_i.rfnoc_image_core_i.b_radio1_5.noc_shell_radio_i.pulse_stretch_min_radio.state
netlist reset -group rfnoc_chdr_rst -sync -async -active_high x4xx_core_i.rfnoc_image_core_i.b_radio1_5.noc_shell_radio_i.backend_iface_i.rfnoc_chdr_rst
netlist reset -group rfnoc_chdr_rst -sync -async -active_low  x4xx_core_i.rfnoc_image_core_i.b_radio1_5.noc_shell_radio_i.backend_iface_i.soft_chdr_rst_stretch_i.state

# ODDR reset
netlist reset -group rfnoc_chdr_rst -async -active_high oddre1_fabric_clk.R_sync


###############################################################################
# Top-Level Port Reset Domains
###############################################################################

netlist reset -group VAsyncReset -async -sync -active_high -virtual VAsyncReset

# Clocking and sync
netlist port resetdomain -reset VAsyncReset [list SYSREF_RF_P]
netlist port resetdomain -reset VAsyncReset [list SYSREF_RF_N]
netlist port resetdomain -reset VAsyncReset [list ADC_CLK_P]
netlist port resetdomain -reset VAsyncReset [list ADC_CLK_N]
netlist port resetdomain -reset VAsyncReset [list DAC_CLK_P]
netlist port resetdomain -reset VAsyncReset [list DAC_CLK_N]

# Analog ports
netlist port resetdomain -reset VAsyncReset [list DB0_RX_P]
netlist port resetdomain -reset VAsyncReset [list DB0_RX_N]
netlist port resetdomain -reset VAsyncReset [list DB1_RX_P]
netlist port resetdomain -reset VAsyncReset [list DB1_RX_N]
netlist port resetdomain -reset VAsyncReset [list DB0_TX_P]
netlist port resetdomain -reset VAsyncReset [list DB0_TX_N]
netlist port resetdomain -reset VAsyncReset [list DB1_TX_P]
netlist port resetdomain -reset VAsyncReset [list DB1_TX_N]

# MGT Reference Clocks
netlist port resetdomain -reset VAsyncReset [list MGT_REFCLK_LMK1_P MGT_REFCLK_LMK1_N]
netlist port resetdomain -reset VAsyncReset [list MGT_REFCLK_LMK2_P MGT_REFCLK_LMK2_N]

# Synchronization sysref
netlist port resetdomain -reset VAsyncReset [list SYSREF_FABRIC_P]
netlist port resetdomain -reset VAsyncReset [list SYSREF_FABRIC_N]

# QSFP signals
netlist port resetdomain -reset VAsyncReset [list QSFP0_0_RX_P]
netlist port resetdomain -reset VAsyncReset [list QSFP0_0_RX_N]
netlist port resetdomain -reset VAsyncReset [list QSFP0_1_RX_P]
netlist port resetdomain -reset VAsyncReset [list QSFP0_1_RX_N]
netlist port resetdomain -reset VAsyncReset [list QSFP0_2_RX_P]
netlist port resetdomain -reset VAsyncReset [list QSFP0_2_RX_N]
netlist port resetdomain -reset VAsyncReset [list QSFP0_3_RX_P]
netlist port resetdomain -reset VAsyncReset [list QSFP0_3_RX_N]
netlist port resetdomain -reset VAsyncReset [list QSFP0_0_TX_P]
netlist port resetdomain -reset VAsyncReset [list QSFP0_0_TX_N]
netlist port resetdomain -reset VAsyncReset [list QSFP0_1_TX_P]
netlist port resetdomain -reset VAsyncReset [list QSFP0_1_TX_N]
netlist port resetdomain -reset VAsyncReset [list QSFP0_2_TX_P]
netlist port resetdomain -reset VAsyncReset [list QSFP0_2_TX_N]
netlist port resetdomain -reset VAsyncReset [list QSFP0_3_TX_P]
netlist port resetdomain -reset VAsyncReset [list QSFP0_3_TX_N]

netlist port resetdomain -reset aReset      [list PPS_IN]
netlist port resetdomain -reset aReset      [list PL_CPLD_MISO]
netlist port resetdomain -reset VAsyncReset [list FPGA_AUX_REF]
netlist port resetdomain -reset VAsyncReset [list QSFP0_MODPRS_n]
netlist port resetdomain -reset VAsyncReset [list QSFP1_MODPRS_n]
netlist port resetdomain -reset aReset      [list DB0_SYNTH_SYNC]
netlist port resetdomain -reset aReset      [list DB1_SYNTH_SYNC]
netlist port resetdomain -reset aReset      [list LMK_SYNC]
netlist port resetdomain -reset aReset      [list PL_CPLD_SCLK]
netlist port resetdomain -reset aReset      [list PL_CPLD_MOSI]
netlist port resetdomain -reset VAsyncReset [list FABRIC_CLK_OUT_P]
netlist port resetdomain -reset VAsyncReset [list FABRIC_CLK_OUT_N]
netlist port resetdomain -reset VAsyncReset [list QSFP0_RESET_n]
netlist port resetdomain -reset VAsyncReset [list QSFP0_LPMODE_n]
netlist port resetdomain -reset VAsyncReset [list QSFP1_RESET_n]
netlist port resetdomain -reset VAsyncReset [list QSFP1_LPMODE_n]
netlist port resetdomain -reset VAsyncReset [list CPLD_JTAG_OE_n]
netlist port resetdomain -reset VAsyncReset [list PPS_LED]
netlist port resetdomain -reset VAsyncReset [list PL_CPLD_JTAGEN]
netlist port resetdomain -reset aReset      [list PL_CPLD_CS0_n]
netlist port resetdomain -reset aReset      [list PL_CPLD_CS1_n]
netlist port resetdomain -reset aReset      [list DB0_GPIO]
netlist port resetdomain -reset aReset      [list DB1_GPIO]
netlist port resetdomain -reset aReset      [list DIOA_FPGA]
netlist port resetdomain -reset aReset      [list DIOB_FPGA]
netlist port resetdomain -reset aReset      [list TRIG_IO]


###############################################################################
# Library Component Models
###############################################################################

# Handshake
hier block handshake -user_specified
hier clock -module handshake clk_a
hier clock -module handshake clk_b
hier reset -module handshake rst_a -sync -active_high
hier port domain -module handshake -clock clk_a \
    [list rst_a valid_a data_a busy_a]
hier port domain -module handshake -clock clk_b \
    [list valid_b data_b]
hier port resetdomain -module handshake -reset rst_a \
    [list valid_a data_a busy_a]


###############################################################################
# Black Box Device Models (Hierarchical Data Models, or HDMs)
###############################################################################

# Note: We describe several of the SystemVerilog blocks as an HDM because
# Questa CDC couldn't handle the SystemVerilog language constructs inside of
# them. Sadly, this means we don't get CDC/RDC coverage inside these modules.
# This applies to:
#
#   eth_ipv4_chdr_dispatch
#   chdr_xport_adapter
#   axi4s_packet_gate
#   axi4s_fifo
#
# The remaining HDM blocks are either IP (for which we don't have source code)
# or known-good library components.

# eth_ipv4_chdr_dispatch
hier block eth_ipv4_chdr_dispatch -user_specified
hier clock -module eth_ipv4_chdr_dispatch eth_rx.clk
hier port domain -module eth_ipv4_chdr_dispatch -clock eth_rx.clk [ list \
    eth_pause_req \
    \
    eth_rx.rst \
    eth_rx.tlast \
    eth_rx.tvalid \
    eth_rx.tready \
    eth_rx.tdata \
    eth_rx.tuser \
    eth_rx.tkeep \
    \
    e2v.clk \
    e2v.rst \
    e2v.tlast \
    e2v.tvalid \
    e2v.tready \
    e2v.tdata \
    e2v.tuser \
    e2v.tkeep \
    \
    e2c.clk \
    e2c.rst \
    e2c.tlast \
    e2c.tvalid \
    e2c.tready \
    e2c.tdata \
    e2c.tuser \
    e2c.tkeep \
    \
    my_mac \
    my_ip \
    my_udp_chdr_port \
    my_pause_set \
    my_pause_clear \
    chdr_dropped \
    cpu_dropped \
]


# chdr_xport_adapter
hier block chdr_xport_adapter -user_specified
hier clock -module chdr_xport_adapter eth_rx.clk
hier port domain -module chdr_xport_adapter -clock eth_rx.clk [ list \
    eth_rx.rst \
    eth_rx.tlast \
    eth_rx.tvalid \
    eth_rx.tready \
    eth_rx.tdata \
    eth_rx.tuser \
    eth_rx.tkeep \
    \
    eth_tx.clk \
    eth_tx.rst \
    eth_tx.tlast \
    eth_tx.tvalid \
    eth_tx.tready \
    eth_tx.tdata \
    eth_tx.tuser \
    eth_tx.tkeep \
    \
    v2e.clk \
    v2e.rst \
    v2e.tlast \
    v2e.tvalid \
    v2e.tready \
    v2e.tdata \
    v2e.tuser \
    v2e.tkeep \
    \
    e2v.clk \
    e2v.rst \
    e2v.tlast \
    e2v.tvalid \
    e2v.tready \
    e2v.tdata \
    e2v.tuser \
    e2v.tkeep \
    \
    device_id \
    my_mac \
    my_ip \
    my_udp_chdr_port \
]


# axi4s_packet_gate
hier block axi4s_packet_gate -user_specified
hier clock -module axi4s_packet_gate i.clk
hier port domain -module axi4s_packet_gate -clock i.clk [ list \
    clear \
    error \
    \
    i.rst \
    i.tlast \
    i.tvalid \
    i.tready \
    i.tdata \
    i.tuser \
    i.tkeep \
    \
    o.clk \
    o.rst \
    o.tlast \
    o.tvalid \
    o.tready \
    o.tdata \
    o.tuser \
    o.tkeep \
]


# axi4s_fifo
hier block axi4s_fifo -user_specified
hier clock -module axi4s_fifo i.clk
hier port domain -module axi4s_fifo -clock i.clk [ list \
    clear \
    \
    i.rst \
    i.tlast \
    i.tvalid \
    i.tready \
    i.tdata \
    i.tuser \
    i.tkeep \
    \
    o.clk \
    o.rst \
    o.tlast \
    o.tvalid \
    o.tready \
    o.tdata \
    o.tuser \
    o.tkeep \
    \
    space \
    occupied \
]


# xge_pcs_pma_common_wrapper
hier block xge_pcs_pma_common_wrapper -user_specified
hier clock -module xge_pcs_pma_common_wrapper refclk
hier clock -module xge_pcs_pma_common_wrapper qpll0outclk
hier clock -module xge_pcs_pma_common_wrapper qpll0outrefclk
hier clock -module xge_pcs_pma_common_wrapper qpll1outclk
hier clock -module xge_pcs_pma_common_wrapper qpll1outrefclk
hier reset -module xge_pcs_pma_common_wrapper qpll0reset -async -active_high
hier reset -module xge_pcs_pma_common_wrapper qpll1reset -async -active_high
hier port resetdomain -module xge_pcs_pma_common_wrapper -reset qpll0reset [ list \
    qpll0lock \
]
hier port resetdomain -module xge_pcs_pma_common_wrapper -reset qpll1reset [ list \
    qpll1lock \
]


# axi_fifo_2clk
hier block axi_fifo_2clk -user_specified
hier clock -module axi_fifo_2clk i_aclk
hier clock -module axi_fifo_2clk o_aclk
hier reset -module axi_fifo_2clk reset -async -active_high
hier port domain -module axi_fifo_2clk -clock i_aclk [ list \
    i_tdata  \
    i_tvalid \
    i_tready \
]
hier port domain -module axi_fifo_2clk -clock o_aclk [ list \
    o_tdata  \
    o_tvalid \
    o_tready \
]
hier port resetdomain -module axi_fifo_2clk -reset reset [list \
    i_tdata  \
    i_tvalid \
    i_tready \
    o_tdata  \
    o_tvalid \
    o_tready \
]


# dds_sin_cos_lut_only
hier block dds_sin_cos_lut_only -user_specified
hier clock -module dds_sin_cos_lut_only aclk
hier reset -module dds_sin_cos_lut_only aresetn -sync -active_low
hier port domain -module dds_sin_cos_lut_only -clock aclk [ list \
    aresetn \
    s_axis_phase_tvalid \
    s_axis_phase_tready \
    s_axis_phase_tlast \
    s_axis_phase_tdata \
    m_axis_data_tvalid \
    m_axis_data_tready \
    m_axis_data_tlast \
    m_axis_data_tdata \
]


# complex_multiplier_dds
hier block complex_multiplier_dds -user_specified
hier clock -module complex_multiplier_dds aclk
hier reset -module complex_multiplier_dds aresetn -sync -active_low
hier port domain -module complex_multiplier_dds -clock aclk [ list \
    aresetn \
    s_axis_a_tvalid \
    s_axis_a_tready \
    s_axis_a_tlast \
    s_axis_a_tdata \
    s_axis_b_tvalid \
    s_axis_b_tready \
    s_axis_b_tlast \
    s_axis_b_tdata \
    m_axis_dout_tvalid \
    m_axis_dout_tready \
    m_axis_dout_tlast \
    m_axis_dout_tdata \
]


# axi_hb47
hier block axi_hb47 -user_specified
hier clock -module axi_hb47 aclk
hier reset -module axi_hb47 aresetn -sync -active_low
hier port domain -module axi_hb47 -clock aclk [ list \
    aresetn \
    s_axis_data_tvalid \
    s_axis_data_tready \
    s_axis_data_tdata \
    m_axis_data_tvalid \
    m_axis_data_tready \
    m_axis_data_tdata \
]


# hbdec1
hier block hbdec1 -user_specified
hier clock -module hbdec1 clk
hier reset -module hbdec1 sclr -sync -active_high
hier port domain -module hbdec1 -clock clk [ list \
    sclr \
    ce \
    coef_ld \
    coef_we \
    coef_din \
    rfd \
    nd \
    din_1 \
    din_2 \
    rdy \
    data_valid \
    dout_1 \
    dout_2 \
]


# hbdec2
hier block hbdec2 -user_specified
hier clock -module hbdec2 clk
hier reset -module hbdec2 sclr -sync -active_high
hier port domain -module hbdec2 -clock clk [ list \
    sclr \
    ce \
    coef_ld \
    coef_we \
    coef_din \
    rfd \
    nd \
    din_1 \
    din_2 \
    rdy \
    data_valid \
    dout_1 \
    dout_2 \
]


# hbdec3
hier block hbdec3 -user_specified
hier clock -module hbdec3 clk
hier reset -module hbdec3 sclr -sync -active_high
hier port domain -module hbdec3 -clock clk [ list \
    sclr \
    ce \
    coef_ld \
    coef_we \
    coef_din \
    rfd \
    nd \
    din_1 \
    din_2 \
    rdy \
    data_valid \
    dout_1 \
    dout_2 \
]


# hb47_2to1
hier block hb47_2to1 -user_specified
hier clock -module hb47_2to1 aclk
hier reset -module hb47_2to1 aresetn -sync -active_low
hier port domain -module hb47_2to1 -clock aclk [ list \
    aresetn            \
    s_axis_data_tvalid \
    s_axis_data_tready \
    s_axis_data_tdata  \
    m_axis_data_tvalid \
    m_axis_data_tuser  \
    m_axis_data_tdata  \
]


# hb47_1to2
hier block hb47_1to2 -user_specified
hier clock -module hb47_1to2 aclk
hier reset -module hb47_1to2 aresetn -sync -active_low
hier port domain -module hb47_1to2 -clock aclk [ list \
    aresetn            \
    s_axis_data_tvalid \
    s_axis_data_tready \
    s_axis_data_tdata  \
    m_axis_data_tvalid \
    m_axis_data_tuser  \
    m_axis_data_tdata  \
]


# x4xx_mgt_io_core
# Questa is not able to analyze this module due to unsupported SystemVerilog
# constructs.
hier block x4xx_mgt_io_core -user_specified
hier clock -module x4xx_mgt_io_core clk100
hier clock -module x4xx_mgt_io_core bus_clk
hier clock -module x4xx_mgt_io_core refclk_p
hier clock -module x4xx_mgt_io_core refclk_n
hier clock -module x4xx_mgt_io_core mgt_clk
hier clock -module x4xx_mgt_io_core m_axi_mac.clk
hier clock -module x4xx_mgt_io_core rx_rec_clk_out
hier clock -module x4xx_mgt_io_core qpll0_clk
hier clock -module x4xx_mgt_io_core qpll0_refclk
hier clock -module x4xx_mgt_io_core qpll1_clk
hier clock -module x4xx_mgt_io_core qpll1_refclk
hier clock -module x4xx_mgt_io_core mgt_rx.clk ; # Unused
hier clock -module x4xx_mgt_io_core mgt_tx.clk ; # Unused
hier clock -module x4xx_mgt_io_core -virtual vclk
hier reset -module x4xx_mgt_io_core areset -async -active_high
# hier reset -module x4xx_mgt_io_core bus_rst -sync -active_high
hier reset -module x4xx_mgt_io_core mgt_rst -sync -active_high
hier reset -module x4xx_mgt_io_core m_axi_mac.rst -sync -active_high
hier port domain -module x4xx_mgt_io_core -clock bus_clk [ list \
    bus_rst     \
    reg_wr_req  \
    reg_wr_addr \
    reg_wr_data \
    reg_rd_req  \
    reg_rd_addr \
    reg_rd_resp \
    reg_rd_data \
    port_info   \
]
hier port domain -module x4xx_mgt_io_core -clock mgt_clk [ list \
    mgt_rst       \
    mgt_pause_req \
    \
    mgt_tx.rst    \
    mgt_tx.tlast  \
    mgt_tx.tvalid \
    mgt_tx.tready \
    mgt_tx.tdata  \
    mgt_tx.tuser  \
    mgt_tx.tkeep  \
    \
    mgt_rx.rst    \
    mgt_rx.tlast  \
    mgt_rx.tvalid \
    mgt_rx.tready \
    mgt_rx.tdata  \
    mgt_rx.tuser  \
    mgt_rx.tkeep  \
]
hier port domain -module x4xx_mgt_io_core -clock m_axi_mac.clk [ list \
    m_axi_mac.rst     \
    m_axi_mac.awaddr  \
    m_axi_mac.awvalid \
    m_axi_mac.awready \
    m_axi_mac.wdata   \
    m_axi_mac.wstrb   \
    m_axi_mac.wvalid  \
    m_axi_mac.wready  \
    m_axi_mac.bresp   \
    m_axi_mac.bvalid  \
    m_axi_mac.bready  \
    m_axi_mac.araddr  \
    m_axi_mac.arvalid \
    m_axi_mac.arready \
    m_axi_mac.rdata   \
    m_axi_mac.rresp   \
    m_axi_mac.rvalid  \
    m_axi_mac.rready  \
    \
    link_up \
    activity \
]
hier port domain -module x4xx_mgt_io_core -clock vclk [ list \
    tx_p         \
    tx_n         \
    rx_p         \
    rx_n         \
    qpll0_reset  \
    qpll0_lock   \
    qpll1_reset  \
    qpll1_lock   \
]


# axi_interconnect_dma_bd
hier block axi_interconnect_dma_bd -user_specified
hier clock -module axi_interconnect_dma_bd clk40
hier reset -module axi_interconnect_dma_bd clk40_rstn -sync -active_low
hier port domain -module axi_interconnect_dma_bd -clock clk40 [ list \
    clk40_rstn            \
                          \
    m_axi_hp_araddr       \
    m_axi_hp_arlen        \
    m_axi_hp_arsize       \
    m_axi_hp_arburst      \
    m_axi_hp_arlock       \
    m_axi_hp_arcache      \
    m_axi_hp_arprot       \
    m_axi_hp_arqos        \
    m_axi_hp_arready      \
    m_axi_hp_arvalid      \
    m_axi_hp_awaddr       \
    m_axi_hp_awlen        \
    m_axi_hp_awsize       \
    m_axi_hp_awburst      \
    m_axi_hp_awlock       \
    m_axi_hp_awcache      \
    m_axi_hp_awprot       \
    m_axi_hp_awqos        \
    m_axi_hp_awready      \
    m_axi_hp_awvalid      \
    m_axi_hp_bready       \
    m_axi_hp_bresp        \
    m_axi_hp_bvalid       \
    m_axi_hp_rdata        \
    m_axi_hp_rready       \
    m_axi_hp_rresp        \
    m_axi_hp_rlast        \
    m_axi_hp_rvalid       \
    m_axi_hp_wdata        \
    m_axi_hp_wready       \
    m_axi_hp_wstrb        \
    m_axi_hp_wlast        \
    m_axi_hp_wvalid       \
                          \
    s_axi_hp_dma0_araddr  \
    s_axi_hp_dma0_arlen   \
    s_axi_hp_dma0_arsize  \
    s_axi_hp_dma0_arburst \
    s_axi_hp_dma0_arlock  \
    s_axi_hp_dma0_arcache \
    s_axi_hp_dma0_arprot  \
    s_axi_hp_dma0_arqos   \
    s_axi_hp_dma0_arready \
    s_axi_hp_dma0_arvalid \
    s_axi_hp_dma0_awaddr  \
    s_axi_hp_dma0_awlen   \
    s_axi_hp_dma0_awsize  \
    s_axi_hp_dma0_awburst \
    s_axi_hp_dma0_awlock  \
    s_axi_hp_dma0_awcache \
    s_axi_hp_dma0_awprot  \
    s_axi_hp_dma0_awqos   \
    s_axi_hp_dma0_awready \
    s_axi_hp_dma0_awvalid \
    s_axi_hp_dma0_bready  \
    s_axi_hp_dma0_bresp   \
    s_axi_hp_dma0_bvalid  \
    s_axi_hp_dma0_rdata   \
    s_axi_hp_dma0_rready  \
    s_axi_hp_dma0_rresp   \
    s_axi_hp_dma0_rlast   \
    s_axi_hp_dma0_rvalid  \
    s_axi_hp_dma0_wdata   \
    s_axi_hp_dma0_wready  \
    s_axi_hp_dma0_wstrb   \
    s_axi_hp_dma0_wlast   \
    s_axi_hp_dma0_wvalid  \
                          \
    s_axi_hp_dma1_araddr  \
    s_axi_hp_dma1_arlen   \
    s_axi_hp_dma1_arsize  \
    s_axi_hp_dma1_arburst \
    s_axi_hp_dma1_arlock  \
    s_axi_hp_dma1_arcache \
    s_axi_hp_dma1_arprot  \
    s_axi_hp_dma1_arqos   \
    s_axi_hp_dma1_arready \
    s_axi_hp_dma1_arvalid \
    s_axi_hp_dma1_awaddr  \
    s_axi_hp_dma1_awlen   \
    s_axi_hp_dma1_awsize  \
    s_axi_hp_dma1_awburst \
    s_axi_hp_dma1_awlock  \
    s_axi_hp_dma1_awcache \
    s_axi_hp_dma1_awprot  \
    s_axi_hp_dma1_awqos   \
    s_axi_hp_dma1_awready \
    s_axi_hp_dma1_awvalid \
    s_axi_hp_dma1_bready  \
    s_axi_hp_dma1_bresp   \
    s_axi_hp_dma1_bvalid  \
    s_axi_hp_dma1_rdata   \
    s_axi_hp_dma1_rready  \
    s_axi_hp_dma1_rresp   \
    s_axi_hp_dma1_rlast   \
    s_axi_hp_dma1_rvalid  \
    s_axi_hp_dma1_wdata   \
    s_axi_hp_dma1_wready  \
    s_axi_hp_dma1_wstrb   \
    s_axi_hp_dma1_wlast   \
    s_axi_hp_dma1_wvalid  \
                          \
    s_axi_hp_dma2_araddr  \
    s_axi_hp_dma2_arlen   \
    s_axi_hp_dma2_arsize  \
    s_axi_hp_dma2_arburst \
    s_axi_hp_dma2_arlock  \
    s_axi_hp_dma2_arcache \
    s_axi_hp_dma2_arprot  \
    s_axi_hp_dma2_arqos   \
    s_axi_hp_dma2_arready \
    s_axi_hp_dma2_arvalid \
    s_axi_hp_dma2_awaddr  \
    s_axi_hp_dma2_awlen   \
    s_axi_hp_dma2_awsize  \
    s_axi_hp_dma2_awburst \
    s_axi_hp_dma2_awlock  \
    s_axi_hp_dma2_awcache \
    s_axi_hp_dma2_awprot  \
    s_axi_hp_dma2_awqos   \
    s_axi_hp_dma2_awready \
    s_axi_hp_dma2_awvalid \
    s_axi_hp_dma2_bready  \
    s_axi_hp_dma2_bresp   \
    s_axi_hp_dma2_bvalid  \
    s_axi_hp_dma2_rdata   \
    s_axi_hp_dma2_rready  \
    s_axi_hp_dma2_rresp   \
    s_axi_hp_dma2_rlast   \
    s_axi_hp_dma2_rvalid  \
    s_axi_hp_dma2_wdata   \
    s_axi_hp_dma2_wready  \
    s_axi_hp_dma2_wstrb   \
    s_axi_hp_dma2_wlast   \
    s_axi_hp_dma2_wvalid  \
                          \
    s_axi_hp_dma3_araddr  \
    s_axi_hp_dma3_arlen   \
    s_axi_hp_dma3_arsize  \
    s_axi_hp_dma3_arburst \
    s_axi_hp_dma3_arlock  \
    s_axi_hp_dma3_arcache \
    s_axi_hp_dma3_arprot  \
    s_axi_hp_dma3_arqos   \
    s_axi_hp_dma3_arready \
    s_axi_hp_dma3_arvalid \
    s_axi_hp_dma3_awaddr  \
    s_axi_hp_dma3_awlen   \
    s_axi_hp_dma3_awsize  \
    s_axi_hp_dma3_awburst \
    s_axi_hp_dma3_awlock  \
    s_axi_hp_dma3_awcache \
    s_axi_hp_dma3_awprot  \
    s_axi_hp_dma3_awqos   \
    s_axi_hp_dma3_awready \
    s_axi_hp_dma3_awvalid \
    s_axi_hp_dma3_bready  \
    s_axi_hp_dma3_bresp   \
    s_axi_hp_dma3_bvalid  \
    s_axi_hp_dma3_rdata   \
    s_axi_hp_dma3_rready  \
    s_axi_hp_dma3_rresp   \
    s_axi_hp_dma3_rlast   \
    s_axi_hp_dma3_rvalid  \
    s_axi_hp_dma3_wdata   \
    s_axi_hp_dma3_wready  \
    s_axi_hp_dma3_wstrb   \
    s_axi_hp_dma3_wlast   \
    s_axi_hp_dma3_wvalid  \
]


# axi_eth_dma_bd
hier block axi_eth_dma_bd -user_specified
hier clock -module axi_eth_dma_bd clk40
hier reset -module axi_eth_dma_bd clk40_rstn -sync -active_low
hier port domain -module axi_eth_dma_bd -clock clk40 [ list \
    clk40_rstn          \
                        \
    c2e_tdata           \
    c2e_tkeep           \
    c2e_tlast           \
    c2e_tready          \
    c2e_tvalid          \
                        \
    e2c_tdata           \
    e2c_tkeep           \
    e2c_tlast           \
    e2c_tready          \
    e2c_tvalid          \
                        \
    axi_eth_dma_araddr  \
    axi_eth_dma_arready \
    axi_eth_dma_arvalid \
    axi_eth_dma_awaddr  \
    axi_eth_dma_awready \
    axi_eth_dma_awvalid \
    axi_eth_dma_bready  \
    axi_eth_dma_bresp   \
    axi_eth_dma_bvalid  \
    axi_eth_dma_rdata   \
    axi_eth_dma_rready  \
    axi_eth_dma_rresp   \
    axi_eth_dma_rvalid  \
    axi_eth_dma_wdata   \
    axi_eth_dma_wready  \
    axi_eth_dma_wvalid  \
                        \
    axi_hp_araddr       \
    axi_hp_arlen        \
    axi_hp_arsize       \
    axi_hp_arburst      \
    axi_hp_arlock       \
    axi_hp_arcache      \
    axi_hp_arprot       \
    axi_hp_arqos        \
    axi_hp_arready      \
    axi_hp_arvalid      \
    axi_hp_awaddr       \
    axi_hp_awlen        \
    axi_hp_awsize       \
    axi_hp_awburst      \
    axi_hp_awlock       \
    axi_hp_awcache      \
    axi_hp_awprot       \
    axi_hp_awqos        \
    axi_hp_awready      \
    axi_hp_awvalid      \
    axi_hp_bready       \
    axi_hp_bresp        \
    axi_hp_bvalid       \
    axi_hp_rdata        \
    axi_hp_rready       \
    axi_hp_rresp        \
    axi_hp_rlast        \
    axi_hp_rvalid       \
    axi_hp_wdata        \
    axi_hp_wready       \
    axi_hp_wstrb        \
    axi_hp_wlast        \
    axi_hp_wvalid       \
                        \
    eth_tx_irq          \
    eth_rx_irq          \
]


# axi_interconnect_eth_bd
hier block axi_interconnect_eth_bd -user_specified
hier clock -module axi_interconnect_eth_bd clk40
hier reset -module axi_interconnect_eth_bd clk40_rstn -sync -active_low
hier port domain -module axi_interconnect_eth_bd -clock clk40 [ list \
    clk40_rstn          \
                        \
    m_axi_dma0_araddr   \
    m_axi_dma0_arready  \
    m_axi_dma0_arvalid  \
    m_axi_dma0_awaddr   \
    m_axi_dma0_awready  \
    m_axi_dma0_awvalid  \
    m_axi_dma0_bready   \
    m_axi_dma0_bresp    \
    m_axi_dma0_bvalid   \
    m_axi_dma0_rdata    \
    m_axi_dma0_rready   \
    m_axi_dma0_rresp    \
    m_axi_dma0_rvalid   \
    m_axi_dma0_wdata    \
    m_axi_dma0_wready   \
    m_axi_dma0_wstrb    \
    m_axi_dma0_wvalid   \
    m_axi_dma0_arprot   \
    m_axi_dma0_awprot   \
                        \
    m_axi_dma1_araddr   \
    m_axi_dma1_arready  \
    m_axi_dma1_arvalid  \
    m_axi_dma1_awaddr   \
    m_axi_dma1_awready  \
    m_axi_dma1_awvalid  \
    m_axi_dma1_bready   \
    m_axi_dma1_bresp    \
    m_axi_dma1_bvalid   \
    m_axi_dma1_rdata    \
    m_axi_dma1_rready   \
    m_axi_dma1_rresp    \
    m_axi_dma1_rvalid   \
    m_axi_dma1_wdata    \
    m_axi_dma1_wready   \
    m_axi_dma1_wstrb    \
    m_axi_dma1_wvalid   \
    m_axi_dma1_arprot   \
    m_axi_dma1_awprot   \
                        \
    m_axi_dma2_araddr   \
    m_axi_dma2_arready  \
    m_axi_dma2_arvalid  \
    m_axi_dma2_awaddr   \
    m_axi_dma2_awready  \
    m_axi_dma2_awvalid  \
    m_axi_dma2_bready   \
    m_axi_dma2_bresp    \
    m_axi_dma2_bvalid   \
    m_axi_dma2_rdata    \
    m_axi_dma2_rready   \
    m_axi_dma2_rresp    \
    m_axi_dma2_rvalid   \
    m_axi_dma2_wdata    \
    m_axi_dma2_wready   \
    m_axi_dma2_wstrb    \
    m_axi_dma2_wvalid   \
    m_axi_dma2_arprot   \
    m_axi_dma2_awprot   \
                        \
    m_axi_dma3_araddr   \
    m_axi_dma3_arready  \
    m_axi_dma3_arvalid  \
    m_axi_dma3_awaddr   \
    m_axi_dma3_awready  \
    m_axi_dma3_awvalid  \
    m_axi_dma3_bready   \
    m_axi_dma3_bresp    \
    m_axi_dma3_bvalid   \
    m_axi_dma3_rdata    \
    m_axi_dma3_rready   \
    m_axi_dma3_rresp    \
    m_axi_dma3_rvalid   \
    m_axi_dma3_wdata    \
    m_axi_dma3_wready   \
    m_axi_dma3_wstrb    \
    m_axi_dma3_wvalid   \
    m_axi_dma3_arprot   \
    m_axi_dma3_awprot   \
                        \
    m_axi_mac0_araddr   \
    m_axi_mac0_arready  \
    m_axi_mac0_arvalid  \
    m_axi_mac0_awaddr   \
    m_axi_mac0_awready  \
    m_axi_mac0_awvalid  \
    m_axi_mac0_bready   \
    m_axi_mac0_bresp    \
    m_axi_mac0_bvalid   \
    m_axi_mac0_rdata    \
    m_axi_mac0_rready   \
    m_axi_mac0_rresp    \
    m_axi_mac0_rvalid   \
    m_axi_mac0_wdata    \
    m_axi_mac0_wready   \
    m_axi_mac0_wstrb    \
    m_axi_mac0_wvalid   \
    m_axi_mac0_arprot   \
    m_axi_mac0_awprot   \
                        \
    m_axi_mac1_araddr   \
    m_axi_mac1_arready  \
    m_axi_mac1_arvalid  \
    m_axi_mac1_awaddr   \
    m_axi_mac1_awready  \
    m_axi_mac1_awvalid  \
    m_axi_mac1_bready   \
    m_axi_mac1_bresp    \
    m_axi_mac1_bvalid   \
    m_axi_mac1_rdata    \
    m_axi_mac1_rready   \
    m_axi_mac1_rresp    \
    m_axi_mac1_rvalid   \
    m_axi_mac1_wdata    \
    m_axi_mac1_wready   \
    m_axi_mac1_wstrb    \
    m_axi_mac1_wvalid   \
    m_axi_mac1_arprot   \
    m_axi_mac1_awprot   \
                        \
    m_axi_mac2_araddr   \
    m_axi_mac2_arready  \
    m_axi_mac2_arvalid  \
    m_axi_mac2_awaddr   \
    m_axi_mac2_awready  \
    m_axi_mac2_awvalid  \
    m_axi_mac2_bready   \
    m_axi_mac2_bresp    \
    m_axi_mac2_bvalid   \
    m_axi_mac2_rdata    \
    m_axi_mac2_rready   \
    m_axi_mac2_rresp    \
    m_axi_mac2_rvalid   \
    m_axi_mac2_wdata    \
    m_axi_mac2_wready   \
    m_axi_mac2_wstrb    \
    m_axi_mac2_wvalid   \
    m_axi_mac2_arprot   \
    m_axi_mac2_awprot   \
                        \
    m_axi_mac3_araddr   \
    m_axi_mac3_arready  \
    m_axi_mac3_arvalid  \
    m_axi_mac3_awaddr   \
    m_axi_mac3_awready  \
    m_axi_mac3_awvalid  \
    m_axi_mac3_bready   \
    m_axi_mac3_bresp    \
    m_axi_mac3_bvalid   \
    m_axi_mac3_rdata    \
    m_axi_mac3_rready   \
    m_axi_mac3_rresp    \
    m_axi_mac3_rvalid   \
    m_axi_mac3_wdata    \
    m_axi_mac3_wready   \
    m_axi_mac3_wstrb    \
    m_axi_mac3_wvalid   \
    m_axi_mac3_arprot   \
    m_axi_mac3_awprot   \
                        \
    m_axi_misc0_araddr  \
    m_axi_misc0_arready \
    m_axi_misc0_arvalid \
    m_axi_misc0_awaddr  \
    m_axi_misc0_awready \
    m_axi_misc0_awvalid \
    m_axi_misc0_bready  \
    m_axi_misc0_bresp   \
    m_axi_misc0_bvalid  \
    m_axi_misc0_rdata   \
    m_axi_misc0_rready  \
    m_axi_misc0_rresp   \
    m_axi_misc0_rvalid  \
    m_axi_misc0_wdata   \
    m_axi_misc0_wready  \
    m_axi_misc0_wstrb   \
    m_axi_misc0_wvalid  \
    m_axi_misc0_arprot  \
    m_axi_misc0_awprot  \
                        \
    m_axi_misc1_araddr  \
    m_axi_misc1_arready \
    m_axi_misc1_arvalid \
    m_axi_misc1_awaddr  \
    m_axi_misc1_awready \
    m_axi_misc1_awvalid \
    m_axi_misc1_bready  \
    m_axi_misc1_bresp   \
    m_axi_misc1_bvalid  \
    m_axi_misc1_rdata   \
    m_axi_misc1_rready  \
    m_axi_misc1_rresp   \
    m_axi_misc1_rvalid  \
    m_axi_misc1_wdata   \
    m_axi_misc1_wready  \
    m_axi_misc1_wstrb   \
    m_axi_misc1_wvalid  \
    m_axi_misc1_arprot  \
    m_axi_misc1_awprot  \
                        \
    m_axi_misc2_araddr  \
    m_axi_misc2_arready \
    m_axi_misc2_arvalid \
    m_axi_misc2_awaddr  \
    m_axi_misc2_awready \
    m_axi_misc2_awvalid \
    m_axi_misc2_bready  \
    m_axi_misc2_bresp   \
    m_axi_misc2_bvalid  \
    m_axi_misc2_rdata   \
    m_axi_misc2_rready  \
    m_axi_misc2_rresp   \
    m_axi_misc2_rvalid  \
    m_axi_misc2_wdata   \
    m_axi_misc2_wready  \
    m_axi_misc2_wstrb   \
    m_axi_misc2_wvalid  \
    m_axi_misc2_arprot  \
    m_axi_misc2_awprot  \
                        \
    m_axi_misc3_araddr  \
    m_axi_misc3_arready \
    m_axi_misc3_arvalid \
    m_axi_misc3_awaddr  \
    m_axi_misc3_awready \
    m_axi_misc3_awvalid \
    m_axi_misc3_bready  \
    m_axi_misc3_bresp   \
    m_axi_misc3_bvalid  \
    m_axi_misc3_rdata   \
    m_axi_misc3_rready  \
    m_axi_misc3_rresp   \
    m_axi_misc3_rvalid  \
    m_axi_misc3_wdata   \
    m_axi_misc3_wready  \
    m_axi_misc3_wstrb   \
    m_axi_misc3_wvalid  \
    m_axi_misc3_arprot  \
    m_axi_misc3_awprot  \
                        \
    s_axi_eth_araddr    \
    s_axi_eth_arready   \
    s_axi_eth_arvalid   \
    s_axi_eth_awaddr    \
    s_axi_eth_awready   \
    s_axi_eth_awvalid   \
    s_axi_eth_bready    \
    s_axi_eth_bresp     \
    s_axi_eth_bvalid    \
    s_axi_eth_rdata     \
    s_axi_eth_rready    \
    s_axi_eth_rresp     \
    s_axi_eth_rvalid    \
    s_axi_eth_wdata     \
    s_axi_eth_wready    \
    s_axi_eth_wstrb     \
    s_axi_eth_wvalid    \
    s_axi_eth_arprot    \
    s_axi_eth_awprot    \
]


# axi_interconnect_app_bd
hier block axi_interconnect_app_bd -user_specified
hier clock -module axi_interconnect_app_bd clk40
hier reset -module axi_interconnect_app_bd clk40_rstn -sync -active_low
hier port domain -module axi_interconnect_app_bd -clock clk40 [ list \
    clk40_rstn          \
                        \
    m_axi_qsfp0_araddr  \
    m_axi_qsfp0_arprot  \
    m_axi_qsfp0_arready \
    m_axi_qsfp0_arvalid \
    m_axi_qsfp0_awaddr  \
    m_axi_qsfp0_awprot  \
    m_axi_qsfp0_awready \
    m_axi_qsfp0_awvalid \
    m_axi_qsfp0_bready  \
    m_axi_qsfp0_bresp   \
    m_axi_qsfp0_bvalid  \
    m_axi_qsfp0_rdata   \
    m_axi_qsfp0_rready  \
    m_axi_qsfp0_rresp   \
    m_axi_qsfp0_rvalid  \
    m_axi_qsfp0_wdata   \
    m_axi_qsfp0_wready  \
    m_axi_qsfp0_wstrb   \
    m_axi_qsfp0_wvalid  \
                        \
    m_axi_qsfp1_araddr  \
    m_axi_qsfp1_arprot  \
    m_axi_qsfp1_arready \
    m_axi_qsfp1_arvalid \
    m_axi_qsfp1_awaddr  \
    m_axi_qsfp1_awprot  \
    m_axi_qsfp1_awready \
    m_axi_qsfp1_awvalid \
    m_axi_qsfp1_bready  \
    m_axi_qsfp1_bresp   \
    m_axi_qsfp1_bvalid  \
    m_axi_qsfp1_rdata   \
    m_axi_qsfp1_rready  \
    m_axi_qsfp1_rresp   \
    m_axi_qsfp1_rvalid  \
    m_axi_qsfp1_wdata   \
    m_axi_qsfp1_wready  \
    m_axi_qsfp1_wstrb   \
    m_axi_qsfp1_wvalid  \
                        \
    s_axi_app_araddr    \
    s_axi_app_arprot    \
    s_axi_app_arready   \
    s_axi_app_arvalid   \
    s_axi_app_awaddr    \
    s_axi_app_awprot    \
    s_axi_app_awready   \
    s_axi_app_awvalid   \
    s_axi_app_bready    \
    s_axi_app_bresp     \
    s_axi_app_bvalid    \
    s_axi_app_rdata     \
    s_axi_app_rready    \
    s_axi_app_rresp     \
    s_axi_app_rvalid    \
    s_axi_app_wdata     \
    s_axi_app_wready    \
    s_axi_app_wstrb     \
    s_axi_app_wvalid    \
]


# adc_400m_bd
hier block adc_400m_bd -user_specified
hier clock -module adc_400m_bd data_clk
hier clock -module adc_400m_bd rfdc_clk
hier clock -module adc_400m_bd rfdc_clk_2x
hier reset -module adc_400m_bd adc_data_out_resetn_dclk -sync -active_low
hier reset -module adc_400m_bd rfdc_adc_axi_resetn_rclk -sync -active_low
hier reset -module adc_400m_bd fir_resetn_rclk2x -sync -active_low
hier port domain -module adc_400m_bd -clock data_clk [ list \
    adc_data_out_resetn_dclk \
    adc_q_data_in_tvalid \
    adc_q_data_in_tready \
    adc_q_data_in_tdata \
    adc_i_data_in_tvalid \
    adc_i_data_in_tready \
    adc_i_data_in_tdata \
    adc_data_out_tvalid \
    adc_data_out_tdata \
]
hier port domain -module adc_400m_bd -clock rfdc_clk [ list \
    rfdc_adc_axi_resetn_rclk \
    enable_data_to_fir_rclk \
]
hier port domain -module adc_400m_bd -clock rfdc_clk_2x [ list \
    fir_resetn_rclk2x \
    swap_iq_2x \
]


# dac_400m_bd
hier block dac_400m_bd -user_specified
hier clock -module dac_400m_bd data_clk
hier clock -module dac_400m_bd data_clk_2x
hier clock -module dac_400m_bd rfdc_clk
hier reset -module dac_400m_bd dac_data_in_resetn_dclk -sync -active_low
hier reset -module dac_400m_bd dac_data_in_resetn_dclk2x -sync -active_low
hier reset -module dac_400m_bd dac_data_in_resetn_rclk -sync -active_low
hier port domain -module dac_400m_bd -clock data_clk [ list \
    dac_data_in_resetn_dclk \
    dac_data_in_tdata       \
    dac_data_in_tready      \
    dac_data_in_tvalid      \
    dac_data_out_tdata      \
    dac_data_out_tready     \
    dac_data_out_tvalid     \
]
hier port domain -module dac_400m_bd -clock data_clk_2x [ list \
    dac_data_in_resetn_dclk2x \
]
hier port domain -module dac_400m_bd -clock rfdc_clk [ list \
    dac_data_in_resetn_rclk \
]


# x4xx_ps_rfdc_bd
hier block x4xx_ps_rfdc_bd -user_specified
# Clock Inputs
hier clock -module x4xx_ps_rfdc_bd bus_clk
hier clock -module x4xx_ps_rfdc_bd clk40
hier clock -module x4xx_ps_rfdc_bd s_axi_hp0_aclk
hier clock -module x4xx_ps_rfdc_bd s_axi_hp1_aclk
hier clock -module x4xx_ps_rfdc_bd s_axi_hpc0_aclk
hier clock -module x4xx_ps_rfdc_bd pll_ref_clk_in
# Clock Outputs
hier clock -module x4xx_ps_rfdc_bd data_clk
hier clock -module x4xx_ps_rfdc_bd data_clk_2x
hier clock -module x4xx_ps_rfdc_bd rfdc_clk
hier clock -module x4xx_ps_rfdc_bd rfdc_clk_2x
hier clock -module x4xx_ps_rfdc_bd pl_clk40
hier clock -module x4xx_ps_rfdc_bd pl_clk100
hier clock -module x4xx_ps_rfdc_bd pl_clk166
hier clock -module x4xx_ps_rfdc_bd pl_clk200
hier clock -module x4xx_ps_rfdc_bd pll_ref_clk_out
# Virtual Clocks
hier clock -module x4xx_ps_rfdc_bd -virtual vclk
# Reset Inputs
hier reset -module x4xx_ps_rfdc_bd clk40_rstn -sync -active_low
hier reset -module x4xx_ps_rfdc_bd bus_rstn -sync -active_low
# bus_clk ports
hier port domain -module x4xx_ps_rfdc_bd -clock bus_clk [ list \
    bus_rstn              \
    s_axis_eth_dma_tdata  \
    s_axis_eth_dma_tkeep  \
    s_axis_eth_dma_tlast  \
    s_axis_eth_dma_tready \
    s_axis_eth_dma_tvalid \
    \
    s_axi_hpc1_awid       \
    s_axi_hpc1_awaddr     \
    s_axi_hpc1_awlen      \
    s_axi_hpc1_awsize     \
    s_axi_hpc1_awburst    \
    s_axi_hpc1_awlock     \
    s_axi_hpc1_awcache    \
    s_axi_hpc1_awprot     \
    s_axi_hpc1_awqos      \
    s_axi_hpc1_awvalid    \
    s_axi_hpc1_awready    \
    s_axi_hpc1_awuser     \
    s_axi_hpc1_wdata      \
    s_axi_hpc1_wstrb      \
    s_axi_hpc1_wlast      \
    s_axi_hpc1_wvalid     \
    s_axi_hpc1_wready     \
    s_axi_hpc1_bid        \
    s_axi_hpc1_bresp      \
    s_axi_hpc1_bvalid     \
    s_axi_hpc1_bready     \
    s_axi_hpc1_arid       \
    s_axi_hpc1_araddr     \
    s_axi_hpc1_arlen      \
    s_axi_hpc1_arsize     \
    s_axi_hpc1_arburst    \
    s_axi_hpc1_arlock     \
    s_axi_hpc1_arcache    \
    s_axi_hpc1_arprot     \
    s_axi_hpc1_arqos      \
    s_axi_hpc1_arvalid    \
    s_axi_hpc1_arready    \
    s_axi_hpc1_rid        \
    s_axi_hpc1_rdata      \
    s_axi_hpc1_rresp      \
    s_axi_hpc1_rlast      \
    s_axi_hpc1_rvalid     \
    s_axi_hpc1_rready     \
    s_axi_hpc1_aruser     \
    \
    m_axis_eth_dma_tdata  \
    m_axis_eth_dma_tkeep  \
    m_axis_eth_dma_tlast  \
    m_axis_eth_dma_tready \
    m_axis_eth_dma_tvalid \
]
hier port domain -module x4xx_ps_rfdc_bd -clock clk40 [ list \
    clk40_rstn                  \
    enable_gated_clocks_clk40   \
    gated_base_clks_valid_clk40 \
    data_clock_locked           \
    rfdc_irq                    \
    \
    rf_axi_status_clk40         \
    rf_dsp_info_clk40           \
    \
    jtag0_tck                   \
    jtag0_tdi                   \
    jtag0_tdo                   \
    jtag0_tms                   \
    \
    m_axi_app_awaddr            \
    m_axi_app_awprot            \
    m_axi_app_awvalid           \
    m_axi_app_awready           \
    m_axi_app_wdata             \
    m_axi_app_wstrb             \
    m_axi_app_wvalid            \
    m_axi_app_wready            \
    m_axi_app_bresp             \
    m_axi_app_bvalid            \
    m_axi_app_bready            \
    m_axi_app_araddr            \
    m_axi_app_arprot            \
    m_axi_app_arvalid           \
    m_axi_app_arready           \
    m_axi_app_rdata             \
    m_axi_app_rresp             \
    m_axi_app_rvalid            \
    m_axi_app_rready            \
    \
    m_axi_eth_internal_awaddr   \
    m_axi_eth_internal_awprot   \
    m_axi_eth_internal_awvalid  \
    m_axi_eth_internal_awready  \
    m_axi_eth_internal_wdata    \
    m_axi_eth_internal_wstrb    \
    m_axi_eth_internal_wvalid   \
    m_axi_eth_internal_wready   \
    m_axi_eth_internal_bresp    \
    m_axi_eth_internal_bvalid   \
    m_axi_eth_internal_bready   \
    m_axi_eth_internal_araddr   \
    m_axi_eth_internal_arprot   \
    m_axi_eth_internal_arvalid  \
    m_axi_eth_internal_arready  \
    m_axi_eth_internal_rdata    \
    m_axi_eth_internal_rresp    \
    m_axi_eth_internal_rvalid   \
    m_axi_eth_internal_rready   \
    \
    m_axi_rpu_awaddr            \
    m_axi_rpu_awprot            \
    m_axi_rpu_awvalid           \
    m_axi_rpu_awready           \
    m_axi_rpu_wdata             \
    m_axi_rpu_wstrb             \
    m_axi_rpu_wvalid            \
    m_axi_rpu_wready            \
    m_axi_rpu_bresp             \
    m_axi_rpu_bvalid            \
    m_axi_rpu_bready            \
    m_axi_rpu_araddr            \
    m_axi_rpu_arprot            \
    m_axi_rpu_arvalid           \
    m_axi_rpu_arready           \
    m_axi_rpu_rdata             \
    m_axi_rpu_rresp             \
    m_axi_rpu_rvalid            \
    m_axi_rpu_rready            \
    \
    m_axi_core_awaddr           \
    m_axi_core_awprot           \
    m_axi_core_awvalid          \
    m_axi_core_awready          \
    m_axi_core_wdata            \
    m_axi_core_wstrb            \
    m_axi_core_wvalid           \
    m_axi_core_wready           \
    m_axi_core_bresp            \
    m_axi_core_bvalid           \
    m_axi_core_bready           \
    m_axi_core_araddr           \
    m_axi_core_arprot           \
    m_axi_core_arvalid          \
    m_axi_core_arready          \
    m_axi_core_rdata            \
    m_axi_core_rresp            \
    m_axi_core_rvalid           \
    m_axi_core_rready           \
    \
    m_axi_mpm_ep_awaddr         \
    m_axi_mpm_ep_awprot         \
    m_axi_mpm_ep_awvalid        \
    m_axi_mpm_ep_awready        \
    m_axi_mpm_ep_wdata          \
    m_axi_mpm_ep_wstrb          \
    m_axi_mpm_ep_wvalid         \
    m_axi_mpm_ep_wready         \
    m_axi_mpm_ep_bresp          \
    m_axi_mpm_ep_bvalid         \
    m_axi_mpm_ep_bready         \
    m_axi_mpm_ep_araddr         \
    m_axi_mpm_ep_arprot         \
    m_axi_mpm_ep_arvalid        \
    m_axi_mpm_ep_arready        \
    m_axi_mpm_ep_rdata          \
    m_axi_mpm_ep_rresp          \
    m_axi_mpm_ep_rvalid         \
    m_axi_mpm_ep_rready         \
]
hier port domain -module x4xx_ps_rfdc_bd -clock data_clk [ list \
    adc_data_out_resetn_dclk \
    adc_reset_pulse_dclk     \
    dac_data_in_resetn_dclk  \
    dac_reset_pulse_dclk     \
    nco_reset_done_dclk      \
    start_nco_reset_dclk     \
]
hier port domain -module x4xx_ps_rfdc_bd -clock data_clk_2x [ list \
    dac_data_in_resetn_dclk2x \
]
hier port domain -module x4xx_ps_rfdc_bd -clock rfdc_clk [ list \
    adc_enable_data_rclk          \
    adc_rfdc_axi_resetn_rclk      \
    dac_data_in_resetn_rclk       \
    enable_sysref_rclk            \
    sysref_out_rclk               \
    \
    adc_tile224_ch0_dout_i_tdata  \
    adc_tile224_ch0_dout_i_tready \
    adc_tile224_ch0_dout_i_tvalid \
    adc_tile224_ch0_dout_q_tdata  \
    adc_tile224_ch0_dout_q_tready \
    adc_tile224_ch0_dout_q_tvalid \
    adc_tile224_ch1_dout_i_tdata  \
    adc_tile224_ch1_dout_i_tready \
    adc_tile224_ch1_dout_i_tvalid \
    adc_tile224_ch1_dout_q_tdata  \
    adc_tile224_ch1_dout_q_tready \
    adc_tile224_ch1_dout_q_tvalid \
    adc_tile226_ch0_dout_i_tdata  \
    adc_tile226_ch0_dout_i_tready \
    adc_tile226_ch0_dout_i_tvalid \
    adc_tile226_ch0_dout_q_tdata  \
    adc_tile226_ch0_dout_q_tready \
    adc_tile226_ch0_dout_q_tvalid \
    adc_tile226_ch1_dout_i_tdata  \
    adc_tile226_ch1_dout_i_tready \
    adc_tile226_ch1_dout_i_tvalid \
    adc_tile226_ch1_dout_q_tdata  \
    adc_tile226_ch1_dout_q_tready \
    adc_tile226_ch1_dout_q_tvalid \
    \
    dac_tile228_ch0_din_tdata     \
    dac_tile228_ch0_din_tvalid    \
    dac_tile228_ch0_din_tready    \
    dac_tile228_ch1_din_tdata     \
    dac_tile228_ch1_din_tvalid    \
    dac_tile228_ch1_din_tready    \
    dac_tile229_ch0_din_tdata     \
    dac_tile229_ch0_din_tvalid    \
    dac_tile229_ch0_din_tready    \
    dac_tile229_ch1_din_tdata     \
    dac_tile229_ch1_din_tvalid    \
    dac_tile229_ch1_din_tready    \
]
hier port domain -module x4xx_ps_rfdc_bd -clock rfdc_clk_2x [ list \
    dac_data_in_resetn_rclk2x \
    fir_resetn_rclk2x         \
    invert_adc_iq_rclk2       \
    invert_dac_iq_rclk2       \
]
hier port domain -module x4xx_ps_rfdc_bd -clock s_axi_hp0_aclk [ list \
    s_axi_hp0_aruser  \
    s_axi_hp0_awuser  \
    s_axi_hp0_awid    \
    s_axi_hp0_awaddr  \
    s_axi_hp0_awlen   \
    s_axi_hp0_awsize  \
    s_axi_hp0_awburst \
    s_axi_hp0_awlock  \
    s_axi_hp0_awcache \
    s_axi_hp0_awprot  \
    s_axi_hp0_awvalid \
    s_axi_hp0_awready \
    s_axi_hp0_wdata   \
    s_axi_hp0_wstrb   \
    s_axi_hp0_wlast   \
    s_axi_hp0_wvalid  \
    s_axi_hp0_wready  \
    s_axi_hp0_bid     \
    s_axi_hp0_bresp   \
    s_axi_hp0_bvalid  \
    s_axi_hp0_bready  \
    s_axi_hp0_arid    \
    s_axi_hp0_araddr  \
    s_axi_hp0_arlen   \
    s_axi_hp0_arsize  \
    s_axi_hp0_arburst \
    s_axi_hp0_arlock  \
    s_axi_hp0_arcache \
    s_axi_hp0_arprot  \
    s_axi_hp0_arvalid \
    s_axi_hp0_arready \
    s_axi_hp0_rid     \
    s_axi_hp0_rdata   \
    s_axi_hp0_rresp   \
    s_axi_hp0_rlast   \
    s_axi_hp0_rvalid  \
    s_axi_hp0_rready  \
    s_axi_hp0_awqos   \
    s_axi_hp0_arqos   \
]
hier port domain -module x4xx_ps_rfdc_bd -clock s_axi_hp1_aclk [ list \
    s_axi_hp1_aruser  \
    s_axi_hp1_awuser  \
    s_axi_hp1_awid    \
    s_axi_hp1_awaddr  \
    s_axi_hp1_awlen   \
    s_axi_hp1_awsize  \
    s_axi_hp1_awburst \
    s_axi_hp1_awlock  \
    s_axi_hp1_awcache \
    s_axi_hp1_awprot  \
    s_axi_hp1_awvalid \
    s_axi_hp1_awready \
    s_axi_hp1_wdata   \
    s_axi_hp1_wstrb   \
    s_axi_hp1_wlast   \
    s_axi_hp1_wvalid  \
    s_axi_hp1_wready  \
    s_axi_hp1_bid     \
    s_axi_hp1_bresp   \
    s_axi_hp1_bvalid  \
    s_axi_hp1_bready  \
    s_axi_hp1_arid    \
    s_axi_hp1_araddr  \
    s_axi_hp1_arlen   \
    s_axi_hp1_arsize  \
    s_axi_hp1_arburst \
    s_axi_hp1_arlock  \
    s_axi_hp1_arcache \
    s_axi_hp1_arprot  \
    s_axi_hp1_arvalid \
    s_axi_hp1_arready \
    s_axi_hp1_rid     \
    s_axi_hp1_rdata   \
    s_axi_hp1_rresp   \
    s_axi_hp1_rlast   \
    s_axi_hp1_rvalid  \
    s_axi_hp1_rready  \
    s_axi_hp1_awqos   \
    s_axi_hp1_arqos   \
]
hier port domain -module x4xx_ps_rfdc_bd -clock s_axi_hpc0_aclk [ list \
    s_axi_hpc0_aruser  \
    s_axi_hpc0_awuser  \
    s_axi_hpc0_awid    \
    s_axi_hpc0_awaddr  \
    s_axi_hpc0_awlen   \
    s_axi_hpc0_awsize  \
    s_axi_hpc0_awburst \
    s_axi_hpc0_awlock  \
    s_axi_hpc0_awcache \
    s_axi_hpc0_awprot  \
    s_axi_hpc0_awvalid \
    s_axi_hpc0_awready \
    s_axi_hpc0_wdata   \
    s_axi_hpc0_wstrb   \
    s_axi_hpc0_wlast   \
    s_axi_hpc0_wvalid  \
    s_axi_hpc0_wready  \
    s_axi_hpc0_bid     \
    s_axi_hpc0_bresp   \
    s_axi_hpc0_bvalid  \
    s_axi_hpc0_bready  \
    s_axi_hpc0_arid    \
    s_axi_hpc0_araddr  \
    s_axi_hpc0_arlen   \
    s_axi_hpc0_arsize  \
    s_axi_hpc0_arburst \
    s_axi_hpc0_arlock  \
    s_axi_hpc0_arcache \
    s_axi_hpc0_arprot  \
    s_axi_hpc0_arvalid \
    s_axi_hpc0_arready \
    s_axi_hpc0_rid     \
    s_axi_hpc0_rdata   \
    s_axi_hpc0_rresp   \
    s_axi_hpc0_rlast   \
    s_axi_hpc0_rvalid  \
    s_axi_hpc0_rready  \
    s_axi_hpc0_awqos   \
    s_axi_hpc0_arqos   \
]
hier port domain -module x4xx_ps_rfdc_bd -clock pll_ref_clk_out [ list \
    sysref_out_pclk \
]
hier port domain -module x4xx_ps_rfdc_bd -clock vclk [ list \
    \
    irq0_lpd_rpu_n                              \
    irq1_lpd_rpu_n                              \
    \
    pl_ps_irq0                                  \
    pl_ps_irq1                                  \
    \
    pl_resetn0                                  \
    pl_resetn1                                  \
    pl_resetn2                                  \
    pl_resetn3                                  \
    \
    sysref_pl_in                                \
    \
    adc0_clk_clk_n                              \
    adc0_clk_clk_p                              \
    adc2_clk_clk_n                              \
    adc2_clk_clk_p                              \
    \
    dac0_clk_clk_n                              \
    dac0_clk_clk_p                              \
    dac1_clk_clk_n                              \
    dac1_clk_clk_p                              \
    \
    gpio_0_tri_i                                \
    gpio_0_tri_o                                \
    gpio_0_tri_t                                \
    \
    dac_tile228_ch0_vout_v_n                    \
    dac_tile228_ch0_vout_v_p                    \
    dac_tile228_ch1_vout_v_n                    \
    dac_tile228_ch1_vout_v_p                    \
    dac_tile229_ch0_vout_v_n                    \
    dac_tile229_ch0_vout_v_p                    \
    dac_tile229_ch1_vout_v_n                    \
    dac_tile229_ch1_vout_v_p                    \
    \
    sysref_rf_in_diff_n                         \
    sysref_rf_in_diff_p                         \
    \
    adc_tile224_ch0_vin_v_n                     \
    adc_tile224_ch0_vin_v_p                     \
    adc_tile224_ch1_vin_v_n                     \
    adc_tile224_ch1_vin_v_p                     \
    adc_tile226_ch0_vin_v_n                     \
    adc_tile226_ch0_vin_v_p                     \
    adc_tile226_ch1_vin_v_n                     \
    adc_tile226_ch1_vin_v_p                     \
]
